services:
  - type: web
    name: solaire-dp-generator
    env: docker
    plan: free
    dockerfilePath: api/Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: HOST
        value: 0.0.0.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: FIREBASE_CONFIG_B64
        sync: false
      - key: FIREBASE_CONFIG
        sync: false
      - key: API_TOKEN
        sync: false
